name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Version
      run: |
        rustup --version
        cargo --version
        cargo clippy --version
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Tests
      run: cargo test --verbose
    - name: Check Benches
      run: cargo check --benches --verbose
    - name: Documentation
      run: cargo doc --verbose
